#### Anupa Sajikumar
#### S3 CSE AIE A Batch

## 01. Web Scrapping
### Can you write a Python script that scrapes (web-scraping) information about the 10 most COVID affected countries with the details (total cases, total deaths, and total recovered) from worldometers.info and write it to a CSV file.

Requesting the web page

In [23]:
import os # for navigating the machine such as file directries
import requests # for requesting urls
import csv # handles csv files
import pandas as pd # handles data
from datetime import datetime # works with date and time
from bs4 import BeautifulSoup as soup # parses web pages
print("Necessary Modules Has Imported Sucessfully!!!")
date = datetime.now().strftime("%Y-%m-%d")

Necessary Modules Has Imported Sucessfully!!!

In [24]:
date

'2023-02-02'

In [25]:
# Defining the URL where the page is accessible
url="https://www.worldometers.info/coronavirus/#countries"
# requesting the url
res = requests.get(url,allow_redirects=True) # res=responses
#headers
res.status_code
# checks if the page requested is done successfully or not

200

In [26]:
res.headers

{'Connection': 'Keep-Alive', 'Content-Type': 'text/html; charset=UTF-8', 'Etag': '"932779439-1675335403;gz"', 'X-LiteSpeed-Cache': 'hit', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Content-Length': '159584', 'Date': 'Thu, 02 Feb 2023 10:57:13 GMT', 'Server': 'LiteSpeed', 'Alt-Svc': 'quic=":443"; ma=2592000; v="43,46", h3-Q043=":443"; ma=2592000, h3-Q046=":443"; ma=2592000, h3-Q050=":443"; ma=2592000, h3-25=":443"; ma=2592000, h3-27=":443"; ma=2592000'}

In [27]:
res.text[:1000]

'\n<!DOCTYPE html>\n<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->\n<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->\n<!--[if !IE]><!-->\n<html lang="en">\n<!--<![endif]-->\n\n\n\n<head>\n    <meta charset="utf-8">\n    <meta http-equiv="X-UA-Compatible" content="IE=edge">\n    <meta name="viewport" content="width=device-width, initial-scale=1">\n\n    <title>COVID - Coronavirus Statistics - Worldometer</title>\n    <meta name="description" content="Daily and weekly updated statistics tracking the number of COVID-19 cases, recovered, and deaths. Historical data with cumulative charts, graphs, and updates.">\n\n\n    \n\t<!-- Favicon -->\n\t<link rel="shortcut icon" href="/favicon/favicon.ico" type="image/x-icon">\n\t<link rel="apple-touch-icon" sizes="57x57" href="/favicon/apple-icon-57x57.png">\n\t<link rel="apple-touch-icon" sizes="60x60" href="/favicon/apple-icon-60x60.png">\n\t<link rel="apple-touch-icon" sizes="72x72" href="/favicon/apple-icon-72x72.png">\n\t<link rel="apple-touch-icon" sizes="'

In [28]:
res.text[:2000]

'\n<!DOCTYPE html>\n<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->\n<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->\n<!--[if !IE]><!-->\n<html lang="en">\n<!--<![endif]-->\n\n\n\n<head>\n    <meta charset="utf-8">\n    <meta http-equiv="X-UA-Compatible" content="IE=edge">\n    <meta name="viewport" content="width=device-width, initial-scale=1">\n\n    <title>COVID - Coronavirus Statistics - Worldometer</title>\n    <meta name="description" content="Daily and weekly updated statistics tracking the number of COVID-19 cases, recovered, and deaths. Historical data with cumulative charts, graphs, and updates.">\n\n\n    \n\t<!-- Favicon -->\n\t<link rel="shortcut icon" href="/favicon/favicon.ico" type="image/x-icon">\n\t<link rel="apple-touch-icon" sizes="57x57" href="/favicon/apple-icon-57x57.png">\n\t<link rel="apple-touch-icon" sizes="60x60" href="/favicon/apple-icon-60x60.png">\n\t<link rel="apple-touch-icon" sizes="72x72" href="/favicon/apple-icon-72x72.png">\n\t<link rel="apple-touch-icon" sizes="76x76" href="/favicon/apple-icon-76x76.png">\n\t<link rel="apple-touch-icon" sizes="114x114" href="/favicon/apple-icon-114x114.png">\n\t<link rel="apple-touch-icon" sizes="120x120" href="/favicon/apple-icon-120x120.png">\n\t<link rel="apple-touch-icon" sizes="144x144" href="/favicon/apple-icon-144x144.png">\n\t<link rel="apple-touch-icon" sizes="152x152" href="/favicon/apple-icon-152x152.png">\n\t<link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-icon-180x180.png">\n\t<link rel="icon" type="image/png" sizes="192x192"  href="/favicon/android-icon-192x192.png">\n\t<link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">\n\t<link rel="icon" type="image/png" sizes="96x96" href="/favicon/favicon-96x96.png">\n\t<link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">\n\t<link rel="manifest" href="/favicon/manifest.json">\n\t<meta name="msapplication-TileColor" content="#ffffff">\n\t<meta name="msapplication-TileImage" content="/favicon/ms-icon-144x1'

Parsing the web page

In [29]:
soup_res = soup(res.text,"html.parser") # parses the text as a beautiful soup object
soup_samp = soup(res.text[:1000],"html.parser")#parses a sample of the text content
soup_samp

<!DOCTYPE html>

<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>COVID - Coronavirus Statistics - Worldometer</title>
<meta content="Daily and weekly updated statistics tracking the number of COVID-19 cases, recovered, and deaths. Historical data with cumulative charts, graphs, and updates." name="description"/>
<!-- Favicon -->
<link href="/favicon/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="/favicon/apple-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
<link href="/favicon/apple-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>
<link href="/favicon/apple-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
	&lt;link rel="apple-touch-icon" sizes="</head></html>

In [30]:
sections = soup_res.find_all("div", id="maincounter-wrap")
sections

[<div id="maincounter-wrap" style="margin-top:15px">
 <h1>Coronavirus Cases:</h1>
 <div class="maincounter-number">
 <span style="color:#aaa">675,491,566        </span>
 </div>
 </div>,
 <div id="maincounter-wrap" style="margin-top:15px">
 <h1>Deaths:</h1>
 <div class="maincounter-number">
 <span>6,764,989</span>
 </div>
 </div>,
 <div id="maincounter-wrap" style="margin-top:15px;">
 <h1>Recovered:</h1>
 <div class="maincounter-number" style="color:#8ACA2B ">
 <span>647,849,700</span>
 </div>
 </div>]

In [31]:
len(sections)

3

In [32]:
for section in sections:
    print("***************")
    print(section)
    print("***************")
    print("\r")

***************
<div id="maincounter-wrap" style="margin-top:15px">
<h1>Coronavirus Cases:</h1>
<div class="maincounter-number">
<span style="color:#aaa">675,491,566        </span>
</div>
</div>
***************

***************
<div id="maincounter-wrap" style="margin-top:15px">
<h1>Deaths:</h1>
<div class="maincounter-number">
<span>6,764,989</span>
</div>
</div>
***************

***************
<div id="maincounter-wrap" style="margin-top:15px;">
<h1>Recovered:</h1>
<div class="maincounter-number" style="color:#8ACA2B ">
<span>647,849,700</span>
</div>
</div>
***************

In [33]:
cases = sections[0].find("span").text.replace(" ","").replace(",","")
deaths = sections[1].find("span").text.replace(",","")
recover = sections[2].find("span").text.replace(",","")
print("Number of cases: {}; Deaths: {}; and Recoveries: {}.".format(cases,deaths,recover))

Number of cases: 675491566; Deaths: 6764989; and Recoveries: 647849700.

Saving the results from the scrape

In [34]:
#Creating the folder
try:
    os.mkdir("./downloads")
except:
    print("Folder exists already ")
    print("Unable to crewate the folder")

Folder exists already
Unable to crewate the folder

In [35]:
# Writing the results in csv file
date=datetime.now().strftime("%d-%m-%Y") #Get the date format as DD-MM-YYYY
print(date)

02-02-2023

In [36]:
variables = ["Cases", "Deaths","Recoveries"]
outfile="./downloads/covid-19-statistics-"+date+".csv"
obs = cases,deaths,recover
print(obs)

('675491566', '6764989', '647849700')

In [37]:
with open(outfile,"w",newline="") as file:
    writer = csv.writer(file)
    writer.writerow(variables)
    writer.writerow(obs)

In [38]:
#Checking the presence of the file in downloads folder or not
os.listdir("./downloads")
# Opening the file and importing the contents of the file
with open(outfile,"r") as f:
    data= f.read()
print(data)

Cases,Deaths,Recoveries
675491566,6764989,647849700

In [39]:
table = soup_res.find("table",id="main_table_countries_today").find("tbody")
rows = table.find_all("tr",style="")

In [40]:
#Extarct the information in each row in the table
table
rows

[<tr class="total_row_world">
 <td></td>
 <td style="text-align:left;">World</td>
 <td>675,491,566</td>
 <td>+26,028</td>
 <td>6,764,989</td>
 <td>+162</td>
 <td>647,849,700</td>
 <td>+71,454</td>
 <td>20,876,877</td>
 <td>41,938</td>
 <td>86,659</td>
 <td>867.9</td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="all" style="display:none">All</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
 <td style="font-weight: bold; text-align:right">104,289,430</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">1,134,259                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">101,378,824</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">1,776,347</td>
 <td style="font-weight: bold; text-align:right">3,425</td>
 <td style="font-weight: bold; text-align:right">311,493</td>
 <td style="font-weight: bold; text-align:right">3,388</td>
 <td style="font-weight: bold; text-align:right">1,160,088,793</td>
 <td style="font-weight: bold; text-align:right">3,464,966</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
 <td data-continent="North America" style="display:none">North America</td>
 <!-- 1 Case/Death/Test every X -->
 <td>3</td><td>295</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">5,306</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
 <td style="font-weight: bold; text-align:right">44,682,895</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">530,740                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">44,150,372</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">1,783</td>
 <td style="font-weight: bold; text-align:right">698</td>
 <td style="font-weight: bold; text-align:right">31,766</td>
 <td style="font-weight: bold; text-align:right">377</td>
 <td style="font-weight: bold; text-align:right">915,265,788</td>
 <td style="font-weight: bold; text-align:right">650,679</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,631,776</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>31</td><td>2,650</td><td>2</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">1</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
 <td style="font-weight: bold; text-align:right">39,528,817</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">164,286                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">39,271,652</span></td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">92,879</td>
 <td style="font-weight: bold; text-align:right">869</td>
 <td style="font-weight: bold; text-align:right">602,716</td>
 <td style="font-weight: bold; text-align:right">2,505</td>
 <td style="font-weight: bold; text-align:right">271,490,188</td>
 <td style="font-weight: bold; text-align:right">4,139,547</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,584,518</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>399</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">1,416</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
 <td style="font-weight: bold; text-align:right">37,796,790</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">165,865                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">37,413,200</td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+15,100</td>
 <td style="text-align:right;font-weight:bold;">217,725</td>
 <td style="font-weight: bold; text-align:right">1,281</td>
 <td style="font-weight: bold; text-align:right">450,586</td>
 <td style="font-weight: bold; text-align:right">1,977</td>
 <td style="font-weight: bold; text-align:right">122,332,384</td>
 <td style="font-weight: bold; text-align:right">1,458,359</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,883,596</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>506</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">2,596</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
 <td style="font-weight: bold; text-align:right">36,837,943</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">697,200                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">35,933,396</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">207,347</td>
 <td style="font-weight: bold; text-align:right">8,318</td>
 <td style="font-weight: bold; text-align:right">171,058</td>
 <td style="font-weight: bold; text-align:right">3,237</td>
 <td style="font-weight: bold; text-align:right">63,776,166</td>
 <td style="font-weight: bold; text-align:right">296,146</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,353,593</a> </td>
 <td data-continent="South America" style="display:none">South America</td>
 <!-- 1 Case/Death/Test every X -->
 <td>6</td><td>309</td><td>3</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">963</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>
 <td style="font-weight: bold; text-align:right">32,588,442</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">68,399                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">21,567,425</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">10,952,618</td>
 <td style="font-weight: bold; text-align:right">496</td>
 <td style="font-weight: bold; text-align:right">259,493</td>
 <td style="font-weight: bold; text-align:right">545</td>
 <td style="font-weight: bold; text-align:right">92,144,639</td>
 <td style="font-weight: bold; text-align:right">733,724</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/japan-population/">125,584,838</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>4</td><td>1,836</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">87,213</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
 <td style="font-weight: bold; text-align:right">30,213,928</td>
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+16,862</td>
 <td style="font-weight: bold; text-align:right;">33,522                                </td>
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+36</td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">29,773,405</span></td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+32,528</td>
 <td style="text-align:right;font-weight:bold;">407,001</td>
 <td style="font-weight: bold; text-align:right">345</td>
 <td style="font-weight: bold; text-align:right">588,622</td>
 <td style="font-weight: bold; text-align:right">653</td>
 <td style="font-weight: bold; text-align:right">15,804,065</td>
 <td style="font-weight: bold; text-align:right">307,892</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,329,899</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>1,531</td><td>3</td>
 <td style="font-weight: bold; text-align:right">329</td>
 <td style="font-weight: bold; text-align:right">0.7</td>
 <td style="font-weight: bold; text-align:right">7,929</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
 <td style="font-weight: bold; text-align:right">25,453,789</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">186,833                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">25,014,986</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">251,970</td>
 <td style="font-weight: bold; text-align:right">205</td>
 <td style="font-weight: bold; text-align:right">422,380</td>
 <td style="font-weight: bold; text-align:right">3,100</td>
 <td style="font-weight: bold; text-align:right">265,478,247</td>
 <td style="font-weight: bold; text-align:right">4,405,344</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,262,770</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>323</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">4,181</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
 <td style="font-weight: bold; text-align:right">24,274,361</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">204,171                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">24,024,750</span></td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+4,662</td>
 <td style="text-align:right;font-weight:bold;">45,440</td>
 <td style="font-weight: bold; text-align:right">146</td>
 <td style="font-weight: bold; text-align:right">354,381</td>
 <td style="font-weight: bold; text-align:right">2,981</td>
 <td style="font-weight: bold; text-align:right">522,526,476</td>
 <td style="font-weight: bold; text-align:right">7,628,357</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,497,907</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>3</td><td>335</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">663</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
 <td style="font-weight: bold; text-align:right">21,958,696</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">395,108                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">21,356,008</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">207,580</td>
 <td style="font-weight: bold; text-align:right">2,300</td>
 <td style="font-weight: bold; text-align:right">150,602</td>
 <td style="font-weight: bold; text-align:right">2,710</td>
 <td style="font-weight: bold; text-align:right">273,400,000</td>
 <td style="font-weight: bold; text-align:right">1,875,095</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,805,947</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>7</td><td>369</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">1,424</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/turkey/">Turkey</a></td>
 <td style="font-weight: bold; text-align:right">17,042,722</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">101,492                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right;">N/A</td>
 <td style="text-align:right;font-weight:bold;">N/A</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">199,186</td>
 <td style="font-weight: bold; text-align:right">1,186</td>
 <td style="font-weight: bold; text-align:right">162,743,369</td>
 <td style="font-weight: bold; text-align:right">1,902,052</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/turkey-population/">85,561,976</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>5</td><td>843</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">1,819</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">12</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>
 <td style="font-weight: bold; text-align:right">13,731,478</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">118,434                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">13,557,699</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">55,345</td>
 <td style="font-weight: bold; text-align:right">231</td>
 <td style="font-weight: bold; text-align:right">293,915</td>
 <td style="font-weight: bold; text-align:right">2,535</td>
 <td style="font-weight: bold; text-align:right">471,036,328</td>
 <td style="font-weight: bold; text-align:right">10,082,298</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/spain-population/">46,719,142</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>3</td><td>394</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">1,185</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">13</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/viet-nam/">Vietnam</a></td>
 <td style="font-weight: bold; text-align:right">11,526,508</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">43,186                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">10,612,479</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">870,843</td>
 <td style="font-weight: bold; text-align:right">2</td>
 <td style="font-weight: bold; text-align:right">116,484</td>
 <td style="font-weight: bold; text-align:right">436</td>
 <td style="font-weight: bold; text-align:right">85,826,548</td>
 <td style="font-weight: bold; text-align:right">867,342</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/viet-nam-population/">98,953,541</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>9</td><td>2,291</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">8,801</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">14</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/australia/">Australia</a></td>

In [41]:
global_info = []
for row in rows:
    columns = row.find_all("td")
    country_info = [column.text.strip() for column in columns]
    del country_info[7]
    global_info.append(country_info)
print(global_info[0:10])
print("\r")
print("Number of rows in tables: {}".format(len(global_info)))
print("\r")

del global_info[0] # delete first row containing world statistics

[['', 'World', '675,491,566', '+26,028', '6,764,989', '+162', '647,849,700', '20,876,877', '41,938', '86,659', '867.9', '', '', '', 'All', '', '', '', '', '', ''], ['1', 'USA', '104,289,430', '', '1,134,259', '', '101,378,824', '1,776,347', '3,425', '311,493', '3,388', '1,160,088,793', '3,464,966', '334,805,269', 'North America', '3', '295', '0', '', '', '5,306'], ['2', 'India', '44,682,895', '', '530,740', '', '44,150,372', '1,783', '698', '31,766', '377', '915,265,788', '650,679', '1,406,631,776', 'Asia', '31', '2,650', '2', '', '', '1'], ['3', 'France', '39,528,817', '', '164,286', '', '39,271,652', '92,879', '869', '602,716', '2,505', '271,490,188', '4,139,547', '65,584,518', 'Europe', '2', '399', '0', '', '', '1,416'], ['4', 'Germany', '37,796,790', '', '165,865', '', '37,413,200', '217,725', '1,281', '450,586', '1,977', '122,332,384', '1,458,359', '83,883,596', 'Europe', '2', '506', '1', '', '', '2,596'], ['5', 'Brazil', '36,837,943', '', '697,200', '', '35,933,396', '207,347', '8,318', '171,058', '3,237', '63,776,166', '296,146', '215,353,593', 'South America', '6', '309', '3', '', '', '963'], ['6', 'Japan', '32,588,442', '', '68,399', '', '21,567,425', '10,952,618', '496', '259,493', '545', '92,144,639', '733,724', '125,584,838', 'Asia', '4', '1,836', '1', '', '', '87,213'], ['7', 'S. Korea', '30,213,928', '+16,862', '33,522', '+36', '29,773,405', '407,001', '345', '588,622', '653', '15,804,065', '307,892', '51,329,899', 'Asia', '2', '1,531', '3', '329', '0.7', '7,929'], ['8', 'Italy', '25,453,789', '', '186,833', '', '25,014,986', '251,970', '205', '422,380', '3,100', '265,478,247', '4,405,344', '60,262,770', 'Europe', '2', '323', '0', '', '', '4,181'], ['9', 'UK', '24,274,361', '', '204,171', '', '24,024,750', '45,440', '146', '354,381', '2,981', '522,526,476', '7,628,357', '68,497,907', 'Europe', '3', '335', '0', '', '', '663']]

Number of rows in tables: 224

In [42]:
try:
    os.mkdir("./downloads")
except:
    print("Already exists")

variables = ["Number","Country"," Total Cases", "New Cases","Total Deaths",
"New Deaths","Total Recovered", "Active Cases","Serious_Critical","Total Cases Per In Pop",
"Death Per In Pop","Total Tests","Tests Per In Pop","Population"]
outfile = "./downloads/covid-19-statistics-"+date+".csv"
print(outfile)
with open(outfile,"w",newline="") as f:
    writer = csv.writer(f)
    writer.writerow(variables)
    for country in global_info:
        writer.writerow(country)

Already exists
./downloads/covid-19-statistics-02-02-2023.csv

In [43]:
data=pd.read_csv(outfile,encoding="ISO-8859-1",index_col=False)
data.head(10)

C:\Users\anupa\AppData\Local\Temp\ipykernel_21228\1040868926.py:1: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  data=pd.read_csv(outfile,encoding="ISO-8859-1",index_col=False)

,Number,Country,Total Cases,New Cases,Total Deaths,New Deaths,Total Recovered,Active Cases,Serious_Critical,Total Cases Per In Pop,Death Per In Pop,Total Tests,Tests Per In Pop,Population
0,1,USA,"104,289,430",NaN,"1,134,259",NaN,"101,378,824","1,776,347","3,425","311,493","3,388","1,160,088,793","3,464,966","334,805,269"
1,2,India,"44,682,895",NaN,"530,740",NaN,"44,150,372","1,783",698,"31,766",377,"915,265,788","650,679","1,406,631,776"
2,3,France,"39,528,817",NaN,"164,286",NaN,"39,271,652","92,879",869,"602,716","2,505","271,490,188","4,139,547","65,584,518"
3,4,Germany,"37,796,790",NaN,"165,865",NaN,"37,413,200","217,725","1,281","450,586","1,977","122,332,384","1,458,359","83,883,596"
4,5,Brazil,"36,837,943",NaN,"697,200",NaN,"35,933,396","207,347","8,318","171,058","3,237","63,776,166","296,146","215,353,593"
5,6,Japan,"32,588,442",NaN,"68,399",NaN,"21,567,425","10,952,618",496,"259,493",545,"92,144,639","733,724","125,584,838"
6,7,S. Korea,"30,213,928","+16,862","33,522",36.0,"29,773,405","407,001",345,"588,622",653,"15,804,065","307,892","51,329,899"
7,8,Italy,"25,453,789",NaN,"186,833",NaN,"25,014,986","251,970",205,"422,380","3,100","265,478,247","4,405,344","60,262,770"
8,9,UK,"24,274,361",NaN,"204,171",NaN,"24,024,750","45,440",146,"354,381","2,981","522,526,476","7,628,357","68,497,907"
9,10,Russia,"21,958,696",NaN,"395,108",NaN,"21,356,008","207,580","2,300","150,602","2,710","273,400,000","1,875,095","145,805,947"

In [44]:
data[data["Country"]=="Russia"]

,Number,Country,Total Cases,New Cases,Total Deaths,New Deaths,Total Recovered,Active Cases,Serious_Critical,Total Cases Per In Pop,Death Per In Pop,Total Tests,Tests Per In Pop,Population
9,10,Russia,"21,958,696",NaN,"395,108",NaN,"21,356,008","207,580","2,300","150,602","2,710","273,400,000","1,875,095","145,805,947"